/******************************************************************************/
/*                 Generated by IBExpert 29/05/2023 11:23:45                  */
/******************************************************************************/

/******************************************************************************/
/*        Following SET SQL DIALECT is just for the Database Comparer         */
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/*                                   Tables                                   */
/******************************************************************************/


CREATE GENERATOR GEN_PRN_TEMPLATE_ID;

CREATE TABLE PRN_TEMPLATE (
    ID             INTEGER NOT NULL,
    TEMPLATENAME   CHAR(30) NOT NULL,
    FIELDDESCR     CHAR(30) NOT NULL,
    FIELDTYPE      CHAR(30) NOT NULL,
    FIELDORDER     INTEGER,
    GROUPBOX       CHAR(10),
    GROUPRIF       CHAR(10),
    POSX           INTEGER,
    POSY           INTEGER,
    WIDTH          INTEGER,
    HEIGHT         INTEGER,
    FIXVALUE       CHAR(100),
    GRIDNAME       CHAR(30),
    GRIDORDER      INTEGER,
    FONTNAME       CHAR(20),
    FONTSIZE       INTEGER,
    FONTSTYLE      CHAR(30),
    FONTCOLOR      CHAR(10),
    FONTALIGN      CHAR(10),
    BACKCOLOR      CHAR(10),
    BORDER         CHAR(10),
    BORDERCOLOR    CHAR(10),
    RECORDSETNAME  CHAR(30),
    FIELDNAME      CHAR(30),
    FIELDSTYLE     CHAR(10),
    REPEAT         CHAR(1) DEFAULT 'A',
    COND_FIELD     CHAR(30),
    COND_VALUE     CHAR(10)
);




/******************************************************************************/
/*                                Primary Keys                                */
/******************************************************************************/

ALTER TABLE PRN_TEMPLATE ADD CONSTRAINT PK_PRN_TEMPLATE PRIMARY KEY (ID);


/******************************************************************************/
/*                                  Triggers                                  */
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/*                            Triggers for tables                             */
/******************************************************************************/



/* Trigger: PRN_TEMPLATE_BI */
CREATE OR ALTER TRIGGER PRN_TEMPLATE_BI FOR PRN_TEMPLATE
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_prn_template_id,1);
end
^


SET TERM ; ^



/******************************************************************************/
/*                            Fields descriptions                             */
/******************************************************************************/

COMMENT ON COLUMN PRN_TEMPLATE.TEMPLATENAME IS 
'nome del template';

COMMENT ON COLUMN PRN_TEMPLATE.FIELDDESCR IS 
'descrizione univoca del campo';

COMMENT ON COLUMN PRN_TEMPLATE.FIELDTYPE IS 
'tipo del campo (riferimento tabella PRN_FIELDTYPE per valori possibili e descrizioni)';

COMMENT ON COLUMN PRN_TEMPLATE.FIELDORDER IS 
'ordinamento assoluto del campo per la stampa';

COMMENT ON COLUMN PRN_TEMPLATE.GROUPBOX IS 
'box x raggruppamento campi con posizionamento Y relativo al campo precedente';

COMMENT ON COLUMN PRN_TEMPLATE.POSX IS 
'posizione asse X del campo (sinistra, centro o destra a seconda del valore presente nel campo FontAlign)';

COMMENT ON COLUMN PRN_TEMPLATE.POSY IS 
'posizione asse Y del campo';

COMMENT ON COLUMN PRN_TEMPLATE.WIDTH IS 
'larghezza massima del campo';

COMMENT ON COLUMN PRN_TEMPLATE.HEIGHT IS 
'altezza massima del campo';

COMMENT ON COLUMN PRN_TEMPLATE.FIXVALUE IS 
'valore fisso o percorso di immagini, loghi, etc';

COMMENT ON COLUMN PRN_TEMPLATE.GRIDNAME IS 
'nome della griglia di cui eventualmente il campo fa parte';

COMMENT ON COLUMN PRN_TEMPLATE.GRIDORDER IS 
'ordine della colonna nella griglia di cui fa parte';

COMMENT ON COLUMN PRN_TEMPLATE.FONTNAME IS 
'nome del font';

COMMENT ON COLUMN PRN_TEMPLATE.FONTSIZE IS 
'dimensione del font';

COMMENT ON COLUMN PRN_TEMPLATE.FONTSTYLE IS 
'stile del font (vuoto, BOLD, ITALIC)';

COMMENT ON COLUMN PRN_TEMPLATE.FONTCOLOR IS 
'colore del font';

COMMENT ON COLUMN PRN_TEMPLATE.FONTALIGN IS 
'allineamento del font (LEFT, CENTER, RIGHT)';

COMMENT ON COLUMN PRN_TEMPLATE.BACKCOLOR IS 
'colore dello sfondo';

COMMENT ON COLUMN PRN_TEMPLATE.BORDER IS 
'stile del bordo della cella della griglia
valori accettati????
NONE
ALL
LEFT
RIGHT
TOP
BOTTOM';

COMMENT ON COLUMN PRN_TEMPLATE.BORDERCOLOR IS 
'colore del bordo della griglia';

COMMENT ON COLUMN PRN_TEMPLATE.RECORDSETNAME IS 
'nome del recordset ';

COMMENT ON COLUMN PRN_TEMPLATE.FIELDNAME IS 
'nome del campo del recordset';

COMMENT ON COLUMN PRN_TEMPLATE.FIELDSTYLE IS 
'stile del campo 
SHRINK 
WRAP';

COMMENT ON COLUMN PRN_TEMPLATE.REPEAT IS 
'Tipo ripetizione campo su pagine
A: all (tutte le pagine)
F: first (solo prima pagina)
L: last (solo ultima pagina)';

COMMENT ON COLUMN PRN_TEMPLATE.COND_FIELD IS 
'Nome del campo su cui verificare la condizione per la stampa';

COMMENT ON COLUMN PRN_TEMPLATE.COND_VALUE IS 
'Valore o condizione che deve essere rispettata dal campo COND_FIELD per stampare il campo corrente';





/**------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

                                                                VALORI INSERITI

**------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/




INSERT INTO PRN_TEMPLATE (ID, TEMPLATENAME, FIELDDESCR, FIELDTYPE, FIELDORDER, GROUPBOX, GROUPRIF, POSX, POSY, WIDTH, HEIGHT, FIXVALUE, GRIDNAME, GRIDORDER, FONTNAME, FONTSIZE, FONTSTYLE, FONTCOLOR, FONTALIGN, BACKCOLOR, BORDER, BORDERCOLOR, RECORDSETNAME, FIELDNAME, FIELDSTYLE, REPEAT, COND_FIELD, COND_VALUE)
                  VALUES (3, 'PREVENTIVI1', 'logo azienda', 'LOGO', 1, 'LOGO', NULL, 10, 10, 70, 15, 'logo.jpg', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO PRN_TEMPLATE (ID, TEMPLATENAME, FIELDDESCR, FIELDTYPE, FIELDORDER, GROUPBOX, GROUPRIF, POSX, POSY, WIDTH, HEIGHT, FIXVALUE, GRIDNAME, GRIDORDER, FONTNAME, FONTSIZE, FONTSTYLE, FONTCOLOR, FONTALIGN, BACKCOLOR, BORDER, BORDERCOLOR, RECORDSETNAME, FIELDNAME, FIELDSTYLE, REPEAT, COND_FIELD, COND_VALUE)
                  VALUES (16, 'PREVENTIVI1', 'tabella', 'GRID', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO PRN_TEMPLATE (ID, TEMPLATENAME, FIELDDESCR, FIELDTYPE, FIELDORDER, GROUPBOX, GROUPRIF, POSX, POSY, WIDTH, HEIGHT, FIXVALUE, GRIDNAME, GRIDORDER, FONTNAME, FONTSIZE, FONTSTYLE, FONTCOLOR, FONTALIGN, BACKCOLOR, BORDER, BORDERCOLOR, RECORDSETNAME, FIELDNAME, FIELDSTYLE, REPEAT, COND_FIELD, COND_VALUE)
                  VALUES (4, 'PREVENTIVI1', 'logo_intest_1', 'LABEL', 2, 'LOGO', NULL, 10, 5, NULL, NULL, 'Via delle Nazioni, 75 - 41122 MODENA', NULL, NULL, 'Arial', 8, NULL, NULL, 'left', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO PRN_TEMPLATE (ID, TEMPLATENAME, FIELDDESCR, FIELDTYPE, FIELDORDER, GROUPBOX, GROUPRIF, POSX, POSY, WIDTH, HEIGHT, FIXVALUE, GRIDNAME, GRIDORDER, FONTNAME, FONTSIZE, FONTSTYLE, FONTCOLOR, FONTALIGN, BACKCOLOR, BORDER, BORDERCOLOR, RECORDSETNAME, FIELDNAME, FIELDSTYLE, REPEAT, COND_FIELD, COND_VALUE)
                  VALUES (5, 'PREVENTIVI1', 'logo_intest_2', 'LABEL', 3, 'LOGO', NULL, 10, 5, NULL, NULL, 'tel: 059-310386 Fax 059-314450', NULL, NULL, 'Arial', 8, NULL, NULL, 'left', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO PRN_TEMPLATE (ID, TEMPLATENAME, FIELDDESCR, FIELDTYPE, FIELDORDER, GROUPBOX, GROUPRIF, POSX, POSY, WIDTH, HEIGHT, FIXVALUE, GRIDNAME, GRIDORDER, FONTNAME, FONTSIZE, FONTSTYLE, FONTCOLOR, FONTALIGN, BACKCOLOR, BORDER, BORDERCOLOR, RECORDSETNAME, FIELDNAME, FIELDSTYLE, REPEAT, COND_FIELD, COND_VALUE)
                  VALUES (6, 'PREVENTIVI1', 'logo_intest_3', 'LABEL', 4, 'LOGO', NULL, 10, 5, NULL, NULL, 'Cap.Soc. 10.400 i.v. R.E.A. Modena n. 309897', NULL, NULL, 'Arial', 8, NULL, NULL, 'left', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO PRN_TEMPLATE (ID, TEMPLATENAME, FIELDDESCR, FIELDTYPE, FIELDORDER, GROUPBOX, GROUPRIF, POSX, POSY, WIDTH, HEIGHT, FIXVALUE, GRIDNAME, GRIDORDER, FONTNAME, FONTSIZE, FONTSTYLE, FONTCOLOR, FONTALIGN, BACKCOLOR, BORDER, BORDERCOLOR, RECORDSETNAME, FIELDNAME, FIELDSTYLE, REPEAT, COND_FIELD, COND_VALUE)
                  VALUES (7, 'PREVENTIVI1', 'logo_intest_4', 'LABEL', 5, 'LOGO', NULL, 10, 5, NULL, NULL, 'Reg.Imprese Modena - C.F. e P.IVA 02532170368', NULL, NULL, 'Arial', 8, NULL, NULL, 'left', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO PRN_TEMPLATE (ID, TEMPLATENAME, FIELDDESCR, FIELDTYPE, FIELDORDER, GROUPBOX, GROUPRIF, POSX, POSY, WIDTH, HEIGHT, FIXVALUE, GRIDNAME, GRIDORDER, FONTNAME, FONTSIZE, FONTSTYLE, FONTCOLOR, FONTALIGN, BACKCOLOR, BORDER, BORDERCOLOR, RECORDSETNAME, FIELDNAME, FIELDSTYLE, REPEAT, COND_FIELD, COND_VALUE)
                  VALUES (8, 'PREVENTIVI1', 'intest_cli', 'LABEL', 6, 'CLIENTE', 'LOGO', 115, 18, NULL, NULL, 'Spett.le', NULL, NULL, 'Arial', 10, NULL, NULL, 'left', NULL, NULL, NULL, NULL, NULL, NULL, 'F', NULL, NULL);
INSERT INTO PRN_TEMPLATE (ID, TEMPLATENAME, FIELDDESCR, FIELDTYPE, FIELDORDER, GROUPBOX, GROUPRIF, POSX, POSY, WIDTH, HEIGHT, FIXVALUE, GRIDNAME, GRIDORDER, FONTNAME, FONTSIZE, FONTSTYLE, FONTCOLOR, FONTALIGN, BACKCOLOR, BORDER, BORDERCOLOR, RECORDSETNAME, FIELDNAME, FIELDSTYLE, REPEAT, COND_FIELD, COND_VALUE)
                  VALUES (9, 'PREVENTIVI1', 'cliente', 'FIELD', 7, 'CLIENTE', 'LOGO', 115, 4, 105, NULL, NULL, NULL, NULL, 'Arial', 10, 'bold', NULL, 'left', NULL, NULL, NULL, 'SQLPREVENTIVO', 'RAGSOC1', 'SHRINK', 'F', NULL, NULL);
INSERT INTO PRN_TEMPLATE (ID, TEMPLATENAME, FIELDDESCR, FIELDTYPE, FIELDORDER, GROUPBOX, GROUPRIF, POSX, POSY, WIDTH, HEIGHT, FIXVALUE, GRIDNAME, GRIDORDER, FONTNAME, FONTSIZE, FONTSTYLE, FONTCOLOR, FONTALIGN, BACKCOLOR, BORDER, BORDERCOLOR, RECORDSETNAME, FIELDNAME, FIELDSTYLE, REPEAT, COND_FIELD, COND_VALUE)
                  VALUES (11, 'PREVENTIVI1', 'cliente_ind', 'FIELD', 9, 'CLIENTE', 'LOGO', 115, 5, 105, NULL, NULL, NULL, NULL, 'Arial', 10, NULL, NULL, 'left', NULL, NULL, NULL, 'SQLPREVENTIVO', 'INDIRI', 'SHRINK', 'F', NULL, NULL);
INSERT INTO PRN_TEMPLATE (ID, TEMPLATENAME, FIELDDESCR, FIELDTYPE, FIELDORDER, GROUPBOX, GROUPRIF, POSX, POSY, WIDTH, HEIGHT, FIXVALUE, GRIDNAME, GRIDORDER, FONTNAME, FONTSIZE, FONTSTYLE, FONTCOLOR, FONTALIGN, BACKCOLOR, BORDER, BORDERCOLOR, RECORDSETNAME, FIELDNAME, FIELDSTYLE, REPEAT, COND_FIELD, COND_VALUE)
                  VALUES (12, 'PREVENTIVI1', 'cliente_locali', 'FIELD', 10, 'CLIENTE', 'LOGO', 115, 4, 105, NULL, NULL, NULL, NULL, 'Arial', 10, NULL, NULL, 'left', NULL, NULL, NULL, 'SQLPREVENTIVO', 'CAP_LOCALI_PROVIN', 'SHRINK', 'F', NULL, NULL);
INSERT INTO PRN_TEMPLATE (ID, TEMPLATENAME, FIELDDESCR, FIELDTYPE, FIELDORDER, GROUPBOX, GROUPRIF, POSX, POSY, WIDTH, HEIGHT, FIXVALUE, GRIDNAME, GRIDORDER, FONTNAME, FONTSIZE, FONTSTYLE, FONTCOLOR, FONTALIGN, BACKCOLOR, BORDER, BORDERCOLOR, RECORDSETNAME, FIELDNAME, FIELDSTYLE, REPEAT, COND_FIELD, COND_VALUE)
                  VALUES (13, 'PREVENTIVI1', 'cliente_naz', 'FIELD', 11, 'CLIENTE', 'LOGO', 115, 4, 105, NULL, NULL, NULL, NULL, 'Arial', 10, NULL, NULL, 'left', NULL, NULL, NULL, 'SQLPREVENTIVO', 'CLI_NAZ', 'SHRINK', 'F', NULL, NULL);
INSERT INTO PRN_TEMPLATE (ID, TEMPLATENAME, FIELDDESCR, FIELDTYPE, FIELDORDER, GROUPBOX, GROUPRIF, POSX, POSY, WIDTH, HEIGHT, FIXVALUE, GRIDNAME, GRIDORDER, FONTNAME, FONTSIZE, FONTSTYLE, FONTCOLOR, FONTALIGN, BACKCOLOR, BORDER, BORDERCOLOR, RECORDSETNAME, FIELDNAME, FIELDSTYLE, REPEAT, COND_FIELD, COND_VALUE)
                  VALUES (1, 'PREVENTIVI1', 'pagina', 'PAGE_FORMAT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A4', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A', NULL, NULL);
INSERT INTO PRN_TEMPLATE (ID, TEMPLATENAME, FIELDDESCR, FIELDTYPE, FIELDORDER, GROUPBOX, GROUPRIF, POSX, POSY, WIDTH, HEIGHT, FIXVALUE, GRIDNAME, GRIDORDER, FONTNAME, FONTSIZE, FONTSTYLE, FONTCOLOR, FONTALIGN, BACKCOLOR, BORDER, BORDERCOLOR, RECORDSETNAME, FIELDNAME, FIELDSTYLE, REPEAT, COND_FIELD, COND_VALUE)
                  VALUES (2, 'PREVENTIVI1', 'orientamento', 'PAGE_ORIENTATION', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'P', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'A', NULL, NULL);
INSERT INTO PRN_TEMPLATE (ID, TEMPLATENAME, FIELDDESCR, FIELDTYPE, FIELDORDER, GROUPBOX, GROUPRIF, POSX, POSY, WIDTH, HEIGHT, FIXVALUE, GRIDNAME, GRIDORDER, FONTNAME, FONTSIZE, FONTSTYLE, FONTCOLOR, FONTALIGN, BACKCOLOR, BORDER, BORDERCOLOR, RECORDSETNAME, FIELDNAME, FIELDSTYLE, REPEAT, COND_FIELD, COND_VALUE)
                  VALUES (14, 'PREVENTIVI1', 'intest', 'LABEL', 15, NULL, NULL, 105, 95, NULL, NULL, 'Preventivo cliente', NULL, NULL, 'Arial', 10, 'bold', NULL, 'center', NULL, NULL, NULL, NULL, NULL, NULL, 'F', NULL, NULL);
INSERT INTO PRN_TEMPLATE (ID, TEMPLATENAME, FIELDDESCR, FIELDTYPE, FIELDORDER, GROUPBOX, GROUPRIF, POSX, POSY, WIDTH, HEIGHT, FIXVALUE, GRIDNAME, GRIDORDER, FONTNAME, FONTSIZE, FONTSTYLE, FONTCOLOR, FONTALIGN, BACKCOLOR, BORDER, BORDERCOLOR, RECORDSETNAME, FIELDNAME, FIELDSTYLE, REPEAT, COND_FIELD, COND_VALUE)
                  VALUES (15, 'PREVENTIVI1', 'intest_line', 'CANVAS_LINE', 16, NULL, NULL, 10, 98, 190, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'F', NULL, NULL);
INSERT INTO PRN_TEMPLATE (ID, TEMPLATENAME, FIELDDESCR, FIELDTYPE, FIELDORDER, GROUPBOX, GROUPRIF, POSX, POSY, WIDTH, HEIGHT, FIXVALUE, GRIDNAME, GRIDORDER, FONTNAME, FONTSIZE, FONTSTYLE, FONTCOLOR, FONTALIGN, BACKCOLOR, BORDER, BORDERCOLOR, RECORDSETNAME, FIELDNAME, FIELDSTYLE, REPEAT, COND_FIELD, COND_VALUE)
                  VALUES (10, 'PREVENTIVI1', 'cliente2', 'FIELD', 8, 'CLIENTE', 'LOGO', 115, 4, 105, NULL, NULL, NULL, NULL, 'Arial', 10, 'bold', NULL, 'left', NULL, NULL, NULL, 'SQLPREVENTIVO', 'RAGSOC2', 'SHRINK', 'F', NULL, NULL);
INSERT INTO PRN_TEMPLATE (ID, TEMPLATENAME, FIELDDESCR, FIELDTYPE, FIELDORDER, GROUPBOX, GROUPRIF, POSX, POSY, WIDTH, HEIGHT, FIXVALUE, GRIDNAME, GRIDORDER, FONTNAME, FONTSIZE, FONTSTYLE, FONTCOLOR, FONTALIGN, BACKCOLOR, BORDER, BORDERCOLOR, RECORDSETNAME, FIELDNAME, FIELDSTYLE, REPEAT, COND_FIELD, COND_VALUE)
                  VALUES (17, 'PREVENTIVI1', 'intest_cli2', 'LABEL', 12, 'CLI_FISC', 'LOGO', 15, 18, NULL, NULL, 'Rappr. fiscale di', NULL, NULL, 'Arial', 10, NULL, NULL, 'left', NULL, NULL, NULL, 'SQLPREVENTIVO', NULL, NULL, 'F', 'RAGSOC3', '<>''''');
INSERT INTO PRN_TEMPLATE (ID, TEMPLATENAME, FIELDDESCR, FIELDTYPE, FIELDORDER, GROUPBOX, GROUPRIF, POSX, POSY, WIDTH, HEIGHT, FIXVALUE, GRIDNAME, GRIDORDER, FONTNAME, FONTSIZE, FONTSTYLE, FONTCOLOR, FONTALIGN, BACKCOLOR, BORDER, BORDERCOLOR, RECORDSETNAME, FIELDNAME, FIELDSTYLE, REPEAT, COND_FIELD, COND_VALUE)
                  VALUES (18, 'PREVENTIVI1', 'cliente3', 'FIELD', 13, 'CLI_FISC', 'LOGO', 15, 4, 105, NULL, NULL, NULL, NULL, 'Arial', 10, 'bold', NULL, 'left', NULL, NULL, NULL, 'SQLPREVENTIVO', 'RAGSOC3', 'SHRINK', 'F', NULL, NULL);
INSERT INTO PRN_TEMPLATE (ID, TEMPLATENAME, FIELDDESCR, FIELDTYPE, FIELDORDER, GROUPBOX, GROUPRIF, POSX, POSY, WIDTH, HEIGHT, FIXVALUE, GRIDNAME, GRIDORDER, FONTNAME, FONTSIZE, FONTSTYLE, FONTCOLOR, FONTALIGN, BACKCOLOR, BORDER, BORDERCOLOR, RECORDSETNAME, FIELDNAME, FIELDSTYLE, REPEAT, COND_FIELD, COND_VALUE)
                  VALUES (19, 'PREVENTIVI1', 'cliente4', 'FIELD', 14, 'CLI_FISC', 'LOGO', 15, 4, 105, NULL, NULL, NULL, NULL, 'Arial', 10, 'bold', NULL, 'left', NULL, NULL, NULL, 'SQLPREVENTIVO', 'RAGSOC4', 'SHRINK', 'F', NULL, NULL);




/******************************************************************************/
/*                 Generated by IBExpert 29/05/2023 11:27:09                  */
/******************************************************************************/

/******************************************************************************/
/*        Following SET SQL DIALECT is just for the Database Comparer         */
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/*                                   Tables                                   */
/******************************************************************************/



CREATE TABLE PRN_FIELDTYPE (
    FIELDTYPE    CHAR(30) NOT NULL,
    DESCRIPTION  CHAR(100),
    NOTES        BLOB SUB_TYPE 1 SEGMENT SIZE 80
);




/******************************************************************************/
/*                                Primary Keys                                */
/******************************************************************************/

ALTER TABLE PRN_FIELDTYPE ADD CONSTRAINT PK_PRN_FIELDTYPE PRIMARY KEY (FIELDTYPE);





INSERT INTO PRN_FIELDTYPE (FIELDTYPE, DESCRIPTION)
                   VALUES ('LOGO', 'logo azienda');
INSERT INTO PRN_FIELDTYPE (FIELDTYPE, DESCRIPTION)
                   VALUES ('SUM', 'somma');
INSERT INTO PRN_FIELDTYPE (FIELDTYPE, DESCRIPTION)
                   VALUES ('GRID', 'tabella');
INSERT INTO PRN_FIELDTYPE (FIELDTYPE, DESCRIPTION)
                   VALUES ('FIELD', 'valore da campo recordset');
INSERT INTO PRN_FIELDTYPE (FIELDTYPE, DESCRIPTION)
                   VALUES ('LABEL', 'etichetta fissa');
INSERT INTO PRN_FIELDTYPE (FIELDTYPE, DESCRIPTION)
                   VALUES ('COLUMN', 'colonna tabella');
INSERT INTO PRN_FIELDTYPE (FIELDTYPE, DESCRIPTION)
                   VALUES ('COLUMNTITLE', 'intestazione colonna tabella');
INSERT INTO PRN_FIELDTYPE (FIELDTYPE, DESCRIPTION)
                   VALUES ('FIELD_SUM', 'valore da campo recordset da sommare per stampa dei campi di tipo SUM');
INSERT INTO PRN_FIELDTYPE (FIELDTYPE, DESCRIPTION)
                   VALUES ('FIELD_SUBTOT', '???');
INSERT INTO PRN_FIELDTYPE (FIELDTYPE, DESCRIPTION)
                   VALUES ('CANVAS_BOX', 'rettangolo da disegnare');
INSERT INTO PRN_FIELDTYPE (FIELDTYPE, DESCRIPTION)
                   VALUES ('CANVAS_LINE', 'linea da disegnare');
INSERT INTO PRN_FIELDTYPE (FIELDTYPE, DESCRIPTION)
                   VALUES ('PAGNUM', 'numeratore di pagina');
INSERT INTO PRN_FIELDTYPE (FIELDTYPE, DESCRIPTION)
                   VALUES ('PAGE_FORMAT', 'formato pagina');
INSERT INTO PRN_FIELDTYPE (FIELDTYPE, DESCRIPTION)
                   VALUES ('PAGE_ORIENTATION', 'orientamento pagina');

COMMIT WORK;








/******************************************************************************/
/*                 Generated by IBExpert 29/05/2023 11:26:04                  */
/******************************************************************************/

/******************************************************************************/
/*        Following SET SQL DIALECT is just for the Database Comparer         */
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/*                                   Tables                                   */
/******************************************************************************/



CREATE TABLE PRN_RECORDSET (
    TEMPLATENAME   CHAR(30) NOT NULL,
    RECORDSETNAME  CHAR(30) NOT NULL,
    SCRIPTSQL      BLOB SUB_TYPE 1 SEGMENT SIZE 80,
    KEYNAME        CHAR(100)
);




/******************************************************************************/
/*                                Primary Keys                                */
/******************************************************************************/

ALTER TABLE PRN_RECORDSET ADD CONSTRAINT PK_PRN_RECORDSET PRIMARY KEY (TEMPLATENAME, RECORDSETNAME);

INSERT INTO PRN_RECORDSET (TEMPLATENAME, RECORDSETNAME, KEYNAME)
                   VALUES ('PREVENTIVI1', 'SQLPREVENTIVO', 'NUMPRE');

COMMIT WORK;
